"""backup table create type column

Revision ID: 0129e4d72198
Revises: 831f269a4d09
Create Date: 2023-04-20 16:12:07.738283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0129e4d72198'
down_revision = '831f269a4d09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup', sa.Column('type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backup', 'type')
    # ### end Alembic commands ###
