"""token table server_name rename to customer

Revision ID: 16d519bc1bad
Revises: 65c689478b6f
Create Date: 2023-05-05 10:57:11.896261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16d519bc1bad'
down_revision = '65c689478b6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token',
        column_name = 'server_name',
        new_column_name = 'customer',
        existing_type=sa.String(255)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token',
        column_name = 'customer',
        new_column_name = 'server_name',
        existing_type=sa.String(255)
    )
    # ### end Alembic commands ###
