"""token table create id column

Revision ID: 524a4ef0d833
Revises: 78ef95e0a672
Create Date: 2023-05-03 14:24:56.339157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524a4ef0d833'
down_revision = '78ef95e0a672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'id')
    # ### end Alembic commands ###
