"""token table server_name add nullable and unique key

Revision ID: 65c689478b6f
Revises: 69553884ec88
Create Date: 2023-05-05 10:55:39.340042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65c689478b6f'
down_revision = '69553884ec88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'server_name',
               existing_type=mysql.VARCHAR(length=55),
               nullable=False)
    op.create_unique_constraint(None, 'token', ['server_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='unique')
    op.alter_column('token', 'server_name',
               existing_type=mysql.VARCHAR(length=55),
               nullable=True)
    # ### end Alembic commands ###
