"""create report_sleep_statistic

Revision ID: 67c8ae4b6321
Revises: 4d6c61b0f027
Create Date: 2023-06-05 14:51:34.661973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c8ae4b6321'
down_revision = '4d6c61b0f027'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_sleep_statistic',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('total_sleep_hrs', sa.Float(), nullable=False),
    sa.Column('total_sleep_hrs_without_missing', sa.Float(), nullable=False),
    sa.Column('missing_times', sa.Integer(), nullable=False),
    sa.Column('awake_times', sa.Integer(), nullable=False),
    sa.Column('rem_times', sa.Integer(), nullable=False),
    sa.Column('light_times', sa.Integer(), nullable=False),
    sa.Column('deep_times', sa.Integer(), nullable=False),
    sa.Column('awake_per_with_awake', sa.Float(), nullable=False),
    sa.Column('rem_per_with_awake', sa.Float(), nullable=False),
    sa.Column('light_per_with_awake', sa.Float(), nullable=False),
    sa.Column('deep_per_with_awake', sa.Float(), nullable=False),
    sa.Column('rem_per_without_awake', sa.Float(), nullable=False),
    sa.Column('light_per_without_awake', sa.Float(), nullable=False),
    sa.Column('deep_per_without_awake', sa.Float(), nullable=False),
    sa.Column('valid_flag', sa.Boolean(), nullable=False),
    sa.Column('create_user', sa.String(length=40), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=False),
    sa.Column('update_user', sa.String(length=40), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.record_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_sleep_statistic')
    # ### end Alembic commands ###
