"""report table create column golden_sample

Revision ID: 69553884ec88
Revises: 524a4ef0d833
Create Date: 2023-05-03 15:31:50.471582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69553884ec88'
down_revision = '524a4ef0d833'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('golden_sample', sa.Boolean(), nullable=True))
    op.drop_index('id_UNIQUE', table_name='token')
    op.create_unique_constraint(None, 'token', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='unique')
    op.create_index('id_UNIQUE', 'token', ['id'], unique=False)
    op.drop_column('report', 'golden_sample')
    # ### end Alembic commands ###
