"""fixed user table unique key

Revision ID: 7f5fcfb66ef6
Revises: 67c8ae4b6321
Create Date: 2023-06-09 11:25:27.050684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f5fcfb66ef6'
down_revision = '67c8ae4b6321'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'email',
               existing_type=mysql.VARCHAR(length=254),
               nullable=False)
    op.create_unique_constraint(None, 'user_profile', ['account'])
    op.create_unique_constraint(None, 'user_profile', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.alter_column('user_profile', 'email',
               existing_type=mysql.VARCHAR(length=254),
               nullable=True)
    # ### end Alembic commands ###
