"""create backup table

Revision ID: 831f269a4d09
Revises: f4ce1452eb43
Create Date: 2023-04-20 15:28:03.471094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831f269a4d09'
down_revision = 'f4ce1452eb43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('back_up_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup')
    # ### end Alembic commands ###
