"""create algo_version column in report table

Revision ID: 8b19d1e6ba7b
Revises: 9b6a56e7d6c3
Create Date: 2023-04-25 15:23:52.002378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b19d1e6ba7b'
down_revision = '9b6a56e7d6c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('algo_version', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'algo_version')
    # ### end Alembic commands ###
