"""line_link create task_status

Revision ID: 997ce8a5717b
Revises: 4cc597f50d0a
Create Date: 2023-04-21 13:42:53.266763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997ce8a5717b'
down_revision = '4cc597f50d0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_link', sa.Column('link_task_status', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_link', 'link_task_status')
    # ### end Alembic commands ###
