"""line_link create valid_flag

Revision ID: 9b6a56e7d6c3
Revises: 997ce8a5717b
Create Date: 2023-04-21 14:11:13.071923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6a56e7d6c3'
down_revision = '997ce8a5717b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_link', sa.Column('valid_flag', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_link', 'valid_flag')
    # ### end Alembic commands ###
