"""token table create expire_datetime

Revision ID: 9dde9394bc03
Revises: 52b89fa8e196
Create Date: 2023-05-05 11:40:27.968081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dde9394bc03'
down_revision = '52b89fa8e196'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('expire_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'expire_datetime')
    # ### end Alembic commands ###
