"""rename token

Revision ID: ea02dab624ff
Revises: 8b19d1e6ba7b
Create Date: 2023-05-03 14:01:05.746764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea02dab624ff'
down_revision = '8b19d1e6ba7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('token_permission', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('token', 'token_permission')
    # ### end Alembic commands ###
