"""report table add basemodel

Revision ID: fa6053564e32
Revises: 2ecb42291895
Create Date: 2023-06-14 10:39:00.711772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6053564e32'
down_revision = '2ecb42291895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.orm import sessionmaker
    from model.report import Report   
    from datetime import datetime
    bind = op.get_bind()
    Session = sessionmaker(bind=bind)
    session = Session()
    op.add_column('report', sa.Column('valid_flag', sa.Boolean(), nullable=True))
    op.add_column('report', sa.Column('create_user', sa.String(length=40), nullable=True))
    op.add_column('report', sa.Column('create_datetime', sa.DateTime(), nullable=True))
    op.add_column('report', sa.Column('update_user', sa.String(length=40), nullable=True))
    op.add_column('report', sa.Column('update_datetime', sa.DateTime(), nullable=True))
    session.query(Report).filter(Report.record_id>=1).update({'valid_flag' : True})
    session.query(Report).filter(Report.record_id>=1).update({'create_user' : "server"})
    session.query(Report).filter(Report.record_id>=1).update({'update_user' : "server"})
    session.query(Report).filter(Report.record_id>=1).update({'create_datetime' : datetime.now()})

    op.alter_column('report', 'valid_flag', existing_type=sa.Boolean(), nullable=False)
    op.alter_column('report', 'create_user', existing_type=sa.String(length=40), nullable=False)
    op.alter_column('report', 'create_datetime', existing_type=sa.DateTime(), nullable=False)
    op.alter_column('report', 'update_user', existing_type=sa.String(length=40), nullable=False)
    op.alter_column('report', 'update_datetime', existing_type=sa.DateTime(), nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'update_datetime')
    op.drop_column('report', 'update_user')
    op.drop_column('report', 'create_datetime')
    op.drop_column('report', 'create_user')
    op.drop_column('report', 'valid_flag')
    # ### end Alembic commands ###
